name: zephyrlab
description: A Zephyr laboratory
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  zephyr:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons_maker: ^0.10.2

flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: assets/icon.png
  image_path_macos: assets/macos_icon.png

flutter:
  uses-material-design: false
